version: "2.1"
services:
  python:
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - WEB_PORT=${WEB_PORT}
      - DB_PORT=${DB_PORT}
    command: [ 'uvicorn', 'main:app', '--reload', '--host', '0.0.0.0', '--port', '6000' ]
    volumes:
      - ./src:/app
    ports:
      - 0.0.0.0:${WEB_PORT}:6000


  postgres:
    restart: unless-stopped
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    hostname: postgres
    ports:
      - 0.0.0.0:${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
volumes:
  postgres-data: